# Generated by Django 4.1.6 on 2023-04-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('ProblemID', models.IntegerField(primary_key=True, serialize=False)),
                ('Statement', models.CharField(max_length=1000)),
                ('Difficuly', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('testcaseID', models.IntegerField(primary_key=True, serialize=False)),
                ('Input', models.CharField(max_length=1000)),
                ('Output', models.CharField(max_length=1000)),
                ('ProblemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemviewer.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('SolutionID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Time_taken', models.TimeField()),
                ('Verdict', models.BooleanField(default=False)),
                ('Failed_test_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problemviewer.testcases')),
                ('ProblemID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problemviewer.problems')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemviewer.user')),
            ],
        ),
    ]
