# Generated by Django 4.1.6 on 2023-04-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemviewer', '0002_problems_problemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='Input',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='Output',
            field=models.DateTimeField(),
        ),
    ]
