# Generated by Django 4.1.6 on 2023-04-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemviewer', '0003_alter_testcases_input_alter_testcases_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='Input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='Output',
            field=models.TextField(),
        ),
    ]
