# Generated by Django 4.1.6 on 2023-04-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemviewer', '0005_alter_testcases_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='ProblemId',
            new_name='ProblemID',
        ),
    ]
