# Generated by Django 4.1.6 on 2023-04-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemviewer', '0006_rename_problemid_testcases_problemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='UserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problemviewer.user'),
        ),
    ]
