# Generated by Django 4.1.6 on 2023-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemviewer', '0007_alter_solutions_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='Submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
